package com.example.cookbook.ui.fragments

import android.os.Bundle
import android.text.Layout
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.cookbook.R
import com.example.cookbook.adapter.recyclerviewadapter.FavoritesAdapter
import com.example.cookbook.data.Meal
import com.example.cookbook.data.Meals
import com.example.cookbook.databinding.FragmentFavoritesBinding






class FavoritesFragment : Fragment() {

    private var _binding : FragmentFavoritesBinding? = null
    private val binding get() = _binding!!
    private lateinit  var adapter : FavoritesAdapter

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        _binding = FragmentFavoritesBinding.inflate(layoutInflater,container,false)

        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        adapter = FavoritesAdapter(Meals(listOf(
            Meal(
                idMeal = "1",
                strMeal = "Teriyaki Chicken",
                strMealAlternate = null,
                strCategory = "Chicken",
                strArea = "Japanese",
                strCountry = "Japan",
                strInstructions = "",
                strMealThumb = R.drawable.hamburger,
                strYoutube = "",
                strTags = "Chicken",
                strIngredient1 = "",
                strIngredient2 = "",
                strIngredient3 = "",
                strIngredient4 = "",
                strIngredient5 = "",
                strIngredient6 = "",
                strIngredient7 = "",
                strIngredient8 = "",
                strIngredient9 = "",
                strIngredient10 = "",
                strIngredient11 = "",
                strIngredient12 = "",
                strIngredient13 = "",
                strIngredient14 = "",
                strIngredient15 = "",
                strIngredient16 = null,
                strIngredient17 = null,
                strIngredient18 = null,
                strIngredient19 = null,
                strIngredient20 = null,
                strMeasure1 = "",
                strMeasure2 = "",
                strMeasure3 = "",
                strMeasure4 = "",
                strMeasure5 = "",
                strMeasure6 = "",
                strMeasure7 = "",
                strMeasure8 = "",
                strMeasure9 = "",
                strMeasure10 = "",
                strMeasure11 = "",
                strMeasure12 = "",
                strMeasure13 = "",
                strMeasure14 = "",
                strMeasure15 = "",
                strMeasure16 = null,
                strMeasure17 = null,
                strMeasure18 = null,
                strMeasure19 = null,
                strMeasure20 = null
            ),

            Meal(
                idMeal = "1",
                strMeal = "Teriyaki Chicken",
                strMealAlternate = null,
                strCategory = "Chicken",
                strArea = "Japanese",
                strCountry = "Japan",
                strInstructions = "",
                strMealThumb = R.drawable.hamburger,
                strYoutube = "",
                strTags = "Chicken",
                strIngredient1 = "",
                strIngredient2 = "",
                strIngredient3 = "",
                strIngredient4 = "",
                strIngredient5 = "",
                strIngredient6 = "",
                strIngredient7 = "",
                strIngredient8 = "",
                strIngredient9 = "",
                strIngredient10 = "",
                strIngredient11 = "",
                strIngredient12 = "",
                strIngredient13 = "",
                strIngredient14 = "",
                strIngredient15 = "",
                strIngredient16 = null,
                strIngredient17 = null,
                strIngredient18 = null,
                strIngredient19 = null,
                strIngredient20 = null,
                strMeasure1 = "",
                strMeasure2 = "",
                strMeasure3 = "",
                strMeasure4 = "",
                strMeasure5 = "",
                strMeasure6 = "",
                strMeasure7 = "",
                strMeasure8 = "",
                strMeasure9 = "",
                strMeasure10 = "",
                strMeasure11 = "",
                strMeasure12 = "",
                strMeasure13 = "",
                strMeasure14 = "",
                strMeasure15 = "",
                strMeasure16 = null,
                strMeasure17 = null,
                strMeasure18 = null,
                strMeasure19 = null,
                strMeasure20 = null
            ),
            Meal(
                idMeal = "1",
                strMeal = "Teriyaki Chicken",
                strMealAlternate = null,
                strCategory = "Chicken",
                strArea = "Japanese",
                strCountry = "Japan",
                strInstructions = "",
                strMealThumb = R.drawable.hamburger,
                strYoutube = "",
                strTags = "Chicken",
                strIngredient1 = "",
                strIngredient2 = "",
                strIngredient3 = "",
                strIngredient4 = "",
                strIngredient5 = "",
                strIngredient6 = "",
                strIngredient7 = "",
                strIngredient8 = "",
                strIngredient9 = "",
                strIngredient10 = "",
                strIngredient11 = "",
                strIngredient12 = "",
                strIngredient13 = "",
                strIngredient14 = "",
                strIngredient15 = "",
                strIngredient16 = null,
                strIngredient17 = null,
                strIngredient18 = null,
                strIngredient19 = null,
                strIngredient20 = null,
                strMeasure1 = "",
                strMeasure2 = "",
                strMeasure3 = "",
                strMeasure4 = "",
                strMeasure5 = "",
                strMeasure6 = "",
                strMeasure7 = "",
                strMeasure8 = "",
                strMeasure9 = "",
                strMeasure10 = "",
                strMeasure11 = "",
                strMeasure12 = "",
                strMeasure13 = "",
                strMeasure14 = "",
                strMeasure15 = "",
                strMeasure16 = null,
                strMeasure17 = null,
                strMeasure18 = null,
                strMeasure19 = null,
                strMeasure20 = null
            ),

            Meal(
                idMeal = "1",
                strMeal = "Teriyaki Chicken",
                strMealAlternate = null,
                strCategory = "Chicken",
                strArea = "Japanese",
                strCountry = "Japan",
                strInstructions = "",
                strMealThumb = R.drawable.hamburger,
                strYoutube = "",
                strTags = "Chicken",
                strIngredient1 = "",
                strIngredient2 = "",
                strIngredient3 = "",
                strIngredient4 = "",
                strIngredient5 = "",
                strIngredient6 = "",
                strIngredient7 = "",
                strIngredient8 = "",
                strIngredient9 = "",
                strIngredient10 = "",
                strIngredient11 = "",
                strIngredient12 = "",
                strIngredient13 = "",
                strIngredient14 = "",
                strIngredient15 = "",
                strIngredient16 = null,
                strIngredient17 = null,
                strIngredient18 = null,
                strIngredient19 = null,
                strIngredient20 = null,
                strMeasure1 = "",
                strMeasure2 = "",
                strMeasure3 = "",
                strMeasure4 = "",
                strMeasure5 = "",
                strMeasure6 = "",
                strMeasure7 = "",
                strMeasure8 = "",
                strMeasure9 = "",
                strMeasure10 = "",
                strMeasure11 = "",
                strMeasure12 = "",
                strMeasure13 = "",
                strMeasure14 = "",
                strMeasure15 = "",
                strMeasure16 = null,
                strMeasure17 = null,
                strMeasure18 = null,
                strMeasure19 = null,
                strMeasure20 = null
            ),
            Meal(
                idMeal = "1",
                strMeal = "Teriyaki Chicken",
                strMealAlternate = null,
                strCategory = "Chicken",
                strArea = "Japanese",
                strCountry = "Japan",
                strInstructions = "",
                strMealThumb = R.drawable.hamburger,
                strYoutube = "",
                strTags = "Chicken",
                strIngredient1 = "",
                strIngredient2 = "",
                strIngredient3 = "",
                strIngredient4 = "",
                strIngredient5 = "",
                strIngredient6 = "",
                strIngredient7 = "",
                strIngredient8 = "",
                strIngredient9 = "",
                strIngredient10 = "",
                strIngredient11 = "",
                strIngredient12 = "",
                strIngredient13 = "",
                strIngredient14 = "",
                strIngredient15 = "",
                strIngredient16 = null,
                strIngredient17 = null,
                strIngredient18 = null,
                strIngredient19 = null,
                strIngredient20 = null,
                strMeasure1 = "",
                strMeasure2 = "",
                strMeasure3 = "",
                strMeasure4 = "",
                strMeasure5 = "",
                strMeasure6 = "",
                strMeasure7 = "",
                strMeasure8 = "",
                strMeasure9 = "",
                strMeasure10 = "",
                strMeasure11 = "",
                strMeasure12 = "",
                strMeasure13 = "",
                strMeasure14 = "",
                strMeasure15 = "",
                strMeasure16 = null,
                strMeasure17 = null,
                strMeasure18 = null,
                strMeasure19 = null,
                strMeasure20 = null
            ),

            Meal(
                idMeal = "1",
                strMeal = "Teriyaki Chicken",
                strMealAlternate = null,
                strCategory = "Chicken",
                strArea = "Japanese",
                strCountry = "Japan",
                strInstructions = "",
                strMealThumb = R.drawable.hamburger,
                strYoutube = "",
                strTags = "Chicken",
                strIngredient1 = "",
                strIngredient2 = "",
                strIngredient3 = "",
                strIngredient4 = "",
                strIngredient5 = "",
                strIngredient6 = "",
                strIngredient7 = "",
                strIngredient8 = "",
                strIngredient9 = "",
                strIngredient10 = "",
                strIngredient11 = "",
                strIngredient12 = "",
                strIngredient13 = "",
                strIngredient14 = "",
                strIngredient15 = "",
                strIngredient16 = null,
                strIngredient17 = null,
                strIngredient18 = null,
                strIngredient19 = null,
                strIngredient20 = null,
                strMeasure1 = "",
                strMeasure2 = "",
                strMeasure3 = "",
                strMeasure4 = "",
                strMeasure5 = "",
                strMeasure6 = "",
                strMeasure7 = "",
                strMeasure8 = "",
                strMeasure9 = "",
                strMeasure10 = "",
                strMeasure11 = "",
                strMeasure12 = "",
                strMeasure13 = "",
                strMeasure14 = "",
                strMeasure15 = "",
                strMeasure16 = null,
                strMeasure17 = null,
                strMeasure18 = null,
                strMeasure19 = null,
                strMeasure20 = null
            ),
        )))

        binding.favoriteRecyclerView.adapter = adapter

        binding.favoriteRecyclerView.layoutManager = LinearLayoutManager(view.context)

        adapter.onItemClick = { mealId ->
            Toast.makeText(requireContext(),"The meal Id: $mealId",Toast.LENGTH_LONG).show()
            val action = FavoritesFragmentDirections.actionFavoritesFragmentToDetailFragment(mealId)
            findNavController().navigate(action)
        }


    }


}