org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

org.gradle.parallel=true

org.gradle.configuration-cache=true


org.gradle.caching=true

org.gradle.configureondemand=true

kotlin.code.style=official

kotlin.incremental=true
org.gradle.tooling.parallel=true
